// packages/frontend/src/pages/financeiro/AnaliseAvancada.vue
<script setup lang="ts">
import { ref, computed } from 'vue'
import { format, startOfMonth, endOfMonth } from 'date-fns'
import api from '../../lib/api'
import PageHeader from '../../components/ui/PageHeader.vue'
import type {
  PaymentMethodAnalytics,
  HourAnalytics,
  DayOfWeekAnalytics,
  ConvenioAnalytics,
  ProcedureAnalytics,
  PatientAnalytics,
  RoomAnalytics,
  CourtesyAnalytics,
} from '../../types'
import { useQuery } from '../../composables/useQuery'

const CHART_COLORS = ['#0e7490', '#0891b2', '#06b6d4', '#22d3ee', '#67e8f9', '#a5f3fc', '#f97316', '#fb923c']

function currency(v: number) {
  return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(v)
}

function pct(value: number, max: number) {
  return max > 0 ? Math.round((value / max) * 100) : 0
}

function truncate(s: string, n: number) {
  return s.length > n ? s.slice(0, n) + '…' : s
}

const startDate = ref(format(startOfMonth(new Date()), 'yyyy-MM-dd'))
const endDate = ref(format(endOfMonth(new Date()), 'yyyy-MM-dd'))

const params = computed(() => ({
  startDate: new Date(startDate.value).toISOString(),
  endDate: new Date(endDate.value + 'T23:59:59').toISOString(),
}))
const queryKeySuffix = computed(() => `${startDate.value}-${endDate.value}`)

const { data: byPaymentRaw, isLoading: loadingPayment } = useQuery<PaymentMethodAnalytics[]>({
  key: computed(() => `analytics-payment-method-${queryKeySuffix.value}`),
  queryFn: () => api.get('/financial/analytics/by-payment-method', { params: params.value }).then(r => r.data),
})
const byPayment = computed(() => byPaymentRaw.value ?? [])

const { data: byHourRaw, isLoading: loadingHour } = useQuery<HourAnalytics[]>({
  key: computed(() => `analytics-by-hour-${queryKeySuffix.value}`),
  queryFn: () => api.get('/financial/analytics/by-hour', { params: params.value }).then(r => r.data),
})
const byHour = computed(() => byHourRaw.value ?? [])

const { data: byDowRaw, isLoading: loadingDow } = useQuery<DayOfWeekAnalytics[]>({
  key: computed(() => `analytics-by-dow-${queryKeySuffix.value}`),
  queryFn: () => api.get('/financial/analytics/by-day-of-week', { params: params.value }).then(r => r.data),
})
const byDow = computed(() => byDowRaw.value ?? [])

const { data: byConvenioRaw, isLoading: loadingConvenio } = useQuery<ConvenioAnalytics[]>({
  key: computed(() => `analytics-by-convenio-${queryKeySuffix.value}`),
  queryFn: () => api.get('/financial/analytics/by-convenio', { params: params.value }).then(r => r.data),
})
const byConvenio = computed(() => byConvenioRaw.value ?? [])

const { data: byProcedureRaw, isLoading: loadingProcedure } = useQuery<ProcedureAnalytics[]>({
  key: computed(() => `analytics-by-procedure-${queryKeySuffix.value}`),
  queryFn: () => api.get('/financial/analytics/by-procedure', { params: params.value }).then(r => r.data),
})
const byProcedure = computed(() => byProcedureRaw.value ?? [])

const { data: byPatientRaw, isLoading: loadingPatient } = useQuery<PatientAnalytics[]>({
  key: computed(() => `analytics-by-patient-${queryKeySuffix.value}`),
  queryFn: () => api.get('/financial/analytics/by-patient', { params: params.value }).then(r => r.data),
})
const byPatient = computed(() => byPatientRaw.value ?? [])

const { data: byRoomRaw, isLoading: loadingRoom } = useQuery<RoomAnalytics[]>({
  key: computed(() => `analytics-by-room-${queryKeySuffix.value}`),
  queryFn: () => api.get('/financial/analytics/by-room', { params: params.value }).then(r => r.data),
})
const byRoom = computed(() => byRoomRaw.value ?? [])

const { data: courtesies } = useQuery<CourtesyAnalytics>({
  key: computed(() => `analytics-courtesies-${queryKeySuffix.value}`),
  queryFn: () => api.get('/financial/analytics/courtesies', { params: params.value }).then(r => r.data),
})

const totalFaturado = computed(() => byPayment.value.reduce((s, r) => s + r.total, 0))
const totalTransacoes = computed(() => byPayment.value.reduce((s, r) => s + r.count, 0))
const ticketMedio = computed(() => (totalTransacoes.value > 0 ? totalFaturado.value / totalTransacoes.value : 0))

// ── Simplified CSS chart data (recharts is not available in the Vue app; see Resumo.vue) ──

// Pie → horizontal bar list with color dot + known percent from API
const paymentBars = computed(() =>
  byPayment.value.map((p, i) => ({
    key: p.method,
    label: p.method,
    value: p.total,
    pct: Math.round(p.percent),
    color: CHART_COLORS[i % CHART_COLORS.length],
    sub: `${p.count} transação${p.count !== 1 ? 'ões' : ''}`,
  }))
)

// Column bar charts → vertical CSS bars (categorical sequences, same pattern as Resumo.vue)
const maxHourTotal = computed(() => Math.max(1, ...byHour.value.map(h => h.total)))
const hourColumns = computed(() =>
  byHour.value.map(h => ({
    key: h.hour,
    label: h.label,
    value: h.total,
    heightPct: pct(h.total, maxHourTotal.value),
    isMax: h.total === maxHourTotal.value && h.total > 0,
  }))
)

const maxDowTotal = computed(() => Math.max(1, ...byDow.value.map(d => d.total)))
const dowColumns = computed(() =>
  byDow.value.map((d, i) => ({
    key: d.dayOfWeek,
    label: d.label,
    value: d.total,
    heightPct: pct(d.total, maxDowTotal.value),
    color: CHART_COLORS[i % 4],
  }))
)

// Horizontal bar charts → AnalyticsBar-style lists
const convenioBars = computed(() => {
  const list = byConvenio.value.slice(0, 8)
  const max = Math.max(1, ...list.map(c => c.total))
  return list.map(c => ({
    key: c.convenio,
    label: truncate(c.convenio, 24),
    value: c.total,
    pct: pct(c.total, max),
  }))
})

const procedureBars = computed(() => {
  const list = byProcedure.value.slice(0, 8)
  const max = Math.max(1, ...list.map(p => p.total))
  return list.map(p => ({
    key: p.procedure,
    label: truncate(p.procedure, 28),
    value: p.total,
    pct: pct(p.total, max),
  }))
})

const patientBars = computed(() => {
  const list = byPatient.value.slice(0, 8)
  const max = Math.max(1, ...list.map(p => p.total))
  return list.map(p => ({
    key: p.id,
    label: truncate(p.name, 24),
    value: p.total,
    pct: pct(p.total, max),
  }))
})

const roomBars = computed(() => {
  const list = byRoom.value.slice(0, 8)
  const max = Math.max(1, ...list.map(r => r.total))
  return list.map(r => ({
    key: r.id,
    label: truncate(r.name, 24),
    value: r.total,
    pct: pct(r.total, max),
  }))
})
</script>

<template>
  <div class="space-y-6 page-stagger">
    <PageHeader title="Análise Avançada" subtitle="Faturamento por forma de pagamento, horário, dia e procedimento" />

    <!-- Filtros -->
    <div class="card py-4">
      <div class="flex flex-wrap items-center gap-3">
        <div class="flex items-center gap-2">
          <label class="text-xs font-medium text-slate-600">De</label>
          <input v-model="startDate" type="date" class="input-field py-1.5 text-sm w-36" />
        </div>
        <div class="flex items-center gap-2">
          <label class="text-xs font-medium text-slate-600">Até</label>
          <input v-model="endDate" type="date" class="input-field py-1.5 text-sm w-36" />
        </div>
      </div>
    </div>

    <!-- KPI tiles -->
    <div class="grid grid-cols-1 sm:grid-cols-4 gap-4">
      <div class="card text-center">
        <p class="text-xs text-slate-500 uppercase tracking-wide font-medium mb-1">Total faturado</p>
        <p class="text-xl font-bold text-slate-900">{{ currency(totalFaturado) }}</p>
      </div>
      <div class="card text-center">
        <p class="text-xs text-slate-500 uppercase tracking-wide font-medium mb-1">Transações</p>
        <p class="text-xl font-bold text-slate-900">{{ totalTransacoes }}</p>
      </div>
      <div class="card text-center">
        <p class="text-xs text-slate-500 uppercase tracking-wide font-medium mb-1">Ticket médio</p>
        <p class="text-xl font-bold text-slate-900">{{ currency(ticketMedio) }}</p>
      </div>
      <div class="card text-center">
        <p class="text-xs text-slate-500 uppercase tracking-wide font-medium mb-1">Cortesias fechadas</p>
        <p class="text-xl font-bold text-slate-900">{{ courtesies?.count ?? 0 }}</p>
      </div>
    </div>

    <!-- Row 1: Forma de Pagamento + Hora do Dia -->
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
      <div class="card">
        <h3 class="text-sm font-semibold text-slate-900 mb-4">Faturamento por Forma de Pagamento</h3>
        <div v-if="loadingPayment" class="h-[280px] skeleton" />
        <div v-else-if="paymentBars.length === 0" class="flex items-center justify-center h-[280px] text-slate-400 text-sm">Sem dados no período</div>
        <div v-else class="space-y-3">
          <div v-for="bar in paymentBars" :key="bar.key">
            <div class="flex items-center justify-between text-xs">
              <span class="text-slate-700 font-medium truncate max-w-[60%] flex items-center gap-1.5">
                <span class="w-2 h-2 rounded-full flex-shrink-0" :style="{ backgroundColor: bar.color }" />
                {{ bar.label }}
              </span>
              <span class="text-slate-500 tabular-nums font-semibold">{{ currency(bar.value) }}</span>
            </div>
            <div class="h-2 bg-slate-100 rounded-full overflow-hidden mt-1">
              <div class="h-full rounded-full transition-all duration-700" :style="{ width: `${bar.pct}%`, backgroundColor: bar.color }" />
            </div>
            <p class="text-xs text-slate-400 mt-0.5">{{ bar.pct }}% · {{ bar.sub }}</p>
          </div>
        </div>
      </div>

      <div class="card">
        <h3 class="text-sm font-semibold text-slate-900 mb-4">Faturamento por Hora do Dia</h3>
        <div v-if="loadingHour" class="h-[280px] skeleton" />
        <div v-else-if="hourColumns.length === 0" class="flex items-center justify-center h-[280px] text-slate-400 text-sm">Sem dados no período</div>
        <div v-else class="flex items-end gap-1 h-[240px]">
          <div v-for="col in hourColumns" :key="col.key" class="flex-1 flex flex-col items-center gap-1.5 min-w-0 h-full justify-end">
            <div class="flex items-end justify-center flex-1 w-full">
              <div
                class="w-full max-w-[14px] rounded-t-md transition-all duration-700"
                :class="col.isMax ? 'bg-primary-600' : 'bg-cyan-400'"
                :style="{ height: `${col.heightPct}%` }"
                :title="`${col.label}: ${currency(col.value)}`"
              />
            </div>
            <span class="text-[10px] text-slate-400 truncate w-full text-center">{{ col.label }}</span>
          </div>
        </div>
      </div>
    </div>

    <!-- Row 2: Dia da Semana + Convênio -->
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
      <div class="card">
        <h3 class="text-sm font-semibold text-slate-900 mb-4">Faturamento por Dia da Semana</h3>
        <div v-if="loadingDow" class="h-[280px] skeleton" />
        <div v-else-if="dowColumns.length === 0" class="flex items-center justify-center h-[280px] text-slate-400 text-sm">Sem dados no período</div>
        <div v-else class="flex items-end gap-2 h-[240px]">
          <div v-for="col in dowColumns" :key="col.key" class="flex-1 flex flex-col items-center gap-1.5 min-w-0 h-full justify-end">
            <div class="flex items-end justify-center flex-1 w-full">
              <div
                class="w-full max-w-[36px] rounded-t-md transition-all duration-700"
                :style="{ height: `${col.heightPct}%`, backgroundColor: col.color }"
                :title="`${col.label}: ${currency(col.value)}`"
              />
            </div>
            <span class="text-[11px] text-slate-400 truncate w-full text-center">{{ col.label }}</span>
          </div>
        </div>
      </div>

      <div class="card">
        <h3 class="text-sm font-semibold text-slate-900 mb-4">Faturamento por Convênio</h3>
        <div v-if="loadingConvenio" class="h-[280px] skeleton" />
        <div v-else-if="convenioBars.length === 0" class="flex items-center justify-center h-[280px] text-slate-400 text-sm">Sem dados no período</div>
        <div v-else class="space-y-3">
          <div v-for="bar in convenioBars" :key="bar.key">
            <div class="flex items-center justify-between text-xs">
              <span class="text-slate-700 font-medium truncate max-w-[60%]">{{ bar.label }}</span>
              <span class="text-slate-500 tabular-nums font-semibold">{{ currency(bar.value) }}</span>
            </div>
            <div class="h-2 bg-slate-100 rounded-full overflow-hidden mt-1">
              <div class="h-full rounded-full bg-cyan-600 transition-all duration-700" :style="{ width: `${bar.pct}%` }" />
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- Row 3: Procedimento (full width) -->
    <div class="card">
      <h3 class="text-sm font-semibold text-slate-900 mb-4">Faturamento por Procedimento</h3>
      <div v-if="loadingProcedure" class="h-[280px] skeleton" />
      <div v-else-if="procedureBars.length === 0" class="flex items-center justify-center h-[280px] text-slate-400 text-sm">Sem dados no período</div>
      <div v-else class="space-y-3">
        <div v-for="bar in procedureBars" :key="bar.key">
          <div class="flex items-center justify-between text-xs">
            <span class="text-slate-700 font-medium truncate max-w-[70%]">{{ bar.label }}</span>
            <span class="text-slate-500 tabular-nums font-semibold">{{ currency(bar.value) }}</span>
          </div>
          <div class="h-2 bg-slate-100 rounded-full overflow-hidden mt-1">
            <div class="h-full rounded-full bg-primary-600 transition-all duration-700" :style="{ width: `${bar.pct}%` }" />
          </div>
        </div>
      </div>
    </div>

    <!-- Row 4: Paciente + Local -->
    <div class="grid grid-cols-1 lg:grid-cols-2 gap-4">
      <div class="card">
        <h3 class="text-sm font-semibold text-slate-900 mb-4">Faturamento por Paciente</h3>
        <div v-if="loadingPatient" class="h-[280px] skeleton" />
        <div v-else-if="patientBars.length === 0" class="flex items-center justify-center h-[280px] text-slate-400 text-sm">Sem dados no período</div>
        <div v-else class="space-y-3">
          <div v-for="bar in patientBars" :key="bar.key">
            <div class="flex items-center justify-between text-xs">
              <span class="text-slate-700 font-medium truncate max-w-[60%]">{{ bar.label }}</span>
              <span class="text-slate-500 tabular-nums font-semibold">{{ currency(bar.value) }}</span>
            </div>
            <div class="h-2 bg-slate-100 rounded-full overflow-hidden mt-1">
              <div class="h-full rounded-full bg-cyan-600 transition-all duration-700" :style="{ width: `${bar.pct}%` }" />
            </div>
          </div>
        </div>
      </div>

      <div class="card">
        <h3 class="text-sm font-semibold text-slate-900 mb-4">Faturamento por Local</h3>
        <div v-if="loadingRoom" class="h-[280px] skeleton" />
        <div v-else-if="roomBars.length === 0" class="flex items-center justify-center h-[280px] text-slate-400 text-sm">Sem dados no período</div>
        <div v-else class="space-y-3">
          <div v-for="bar in roomBars" :key="bar.key">
            <div class="flex items-center justify-between text-xs">
              <span class="text-slate-700 font-medium truncate max-w-[60%]">{{ bar.label }}</span>
              <span class="text-slate-500 tabular-nums font-semibold">{{ currency(bar.value) }}</span>
            </div>
            <div class="h-2 bg-slate-100 rounded-full overflow-hidden mt-1">
              <div class="h-full rounded-full bg-cyan-400 transition-all duration-700" :style="{ width: `${bar.pct}%` }" />
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

// packages/frontend/src/pages/financeiro/AnaliseAvancada.tsx
import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { format, startOfMonth, endOfMonth } from 'date-fns'
import {
  BarChart,
  Bar,
  XAxis,
  YAxis,
  CartesianGrid,
  Tooltip,
  ResponsiveContainer,
  PieChart,
  Pie,
  Cell,
  Legend,
} from 'recharts'
import api from '../../lib/api'
import PageHeader from '../../components/ui/PageHeader'
import type {
  PaymentMethodAnalytics,
  HourAnalytics,
  DayOfWeekAnalytics,
  ConvenioAnalytics,
  ProcedureAnalytics,
  PatientAnalytics,
  RoomAnalytics,
  CourtesyAnalytics,
} from '../../types'

const CHART_COLORS = ['#0e7490', '#0891b2', '#06b6d4', '#22d3ee', '#67e8f9', '#a5f3fc', '#f97316', '#fb923c']

function currency(v: number) {
  return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(v)
}

function yAxisFormatter(v: number) {
  if (v >= 1000) return `R$${(v / 1000).toFixed(0)}k`
  return `R$${v}`
}

const CustomTooltip = ({ active, payload, label }: { active?: boolean; payload?: Array<{ value: number; color: string; name: string }>; label?: string }) => {
  if (!active || !payload?.length) return null
  return (
    <div className="bg-white border border-slate-200 rounded-xl shadow-lg px-3 py-2 text-sm">
      <p className="font-semibold text-slate-700 mb-1">{label}</p>
      {payload.map((p, i) => (
        <p key={i} style={{ color: p.color }}>{currency(p.value)}</p>
      ))}
    </div>
  )
}

function SkeletonCard() {
  return (
    <div className="card animate-pulse">
      <div className="h-4 bg-slate-200 rounded w-1/2 mb-4" />
      <div className="h-[280px] bg-slate-100 rounded-xl" />
    </div>
  )
}

function StatTile({ label, value }: { label: string; value: string }) {
  return (
    <div className="card text-center">
      <p className="text-xs text-slate-500 uppercase tracking-wide font-medium mb-1">{label}</p>
      <p className="text-xl font-bold text-slate-900">{value}</p>
    </div>
  )
}

export default function AnaliseAvancada() {
  const [startDate, setStartDate] = useState(format(startOfMonth(new Date()), 'yyyy-MM-dd'))
  const [endDate, setEndDate] = useState(format(endOfMonth(new Date()), 'yyyy-MM-dd'))

  const params = {
    startDate: new Date(startDate).toISOString(),
    endDate: new Date(endDate + 'T23:59:59').toISOString(),
  }

  const { data: byPayment = [], isLoading: loadingPayment } = useQuery<PaymentMethodAnalytics[]>({
    queryKey: ['analytics-payment-method', startDate, endDate],
    queryFn: () => api.get('/financial/analytics/by-payment-method', { params }).then(r => r.data),
  })

  const { data: byHour = [], isLoading: loadingHour } = useQuery<HourAnalytics[]>({
    queryKey: ['analytics-by-hour', startDate, endDate],
    queryFn: () => api.get('/financial/analytics/by-hour', { params }).then(r => r.data),
  })

  const { data: byDow = [], isLoading: loadingDow } = useQuery<DayOfWeekAnalytics[]>({
    queryKey: ['analytics-by-dow', startDate, endDate],
    queryFn: () => api.get('/financial/analytics/by-day-of-week', { params }).then(r => r.data),
  })

  const { data: byConvenio = [], isLoading: loadingConvenio } = useQuery<ConvenioAnalytics[]>({
    queryKey: ['analytics-by-convenio', startDate, endDate],
    queryFn: () => api.get('/financial/analytics/by-convenio', { params }).then(r => r.data),
  })

  const { data: byProcedure = [], isLoading: loadingProcedure } = useQuery<ProcedureAnalytics[]>({
    queryKey: ['analytics-by-procedure', startDate, endDate],
    queryFn: () => api.get('/financial/analytics/by-procedure', { params }).then(r => r.data),
  })

  const { data: byPatient = [], isLoading: loadingPatient } = useQuery<PatientAnalytics[]>({
    queryKey: ['analytics-by-patient', startDate, endDate],
    queryFn: () => api.get('/financial/analytics/by-patient', { params }).then(r => r.data),
  })

  const { data: byRoom = [], isLoading: loadingRoom } = useQuery<RoomAnalytics[]>({
    queryKey: ['analytics-by-room', startDate, endDate],
    queryFn: () => api.get('/financial/analytics/by-room', { params }).then(r => r.data),
  })

  const { data: courtesies } = useQuery<CourtesyAnalytics>({
    queryKey: ['analytics-courtesies', startDate, endDate],
    queryFn: () => api.get('/financial/analytics/courtesies', { params }).then(r => r.data),
  })

  const totalFaturado = byPayment.reduce((s, r) => s + r.total, 0)
  const totalTransacoes = byPayment.reduce((s, r) => s + r.count, 0)
  const ticketMedio = totalTransacoes > 0 ? totalFaturado / totalTransacoes : 0

  const maxHourTotal = byHour.length > 0 ? Math.max(...byHour.map(h => h.total)) : 1

  const pieData = byPayment.map((p, i) => ({
    name: p.method,
    value: p.total,
    fill: CHART_COLORS[i % CHART_COLORS.length],
  }))

  const hourBarData = byHour.map(h => ({
    name: h.label,
    Faturamento: h.total,
    fill: h.total === maxHourTotal ? CHART_COLORS[0] : CHART_COLORS[2],
  }))

  const dowBarData = byDow.map((d, i) => ({
    name: d.label,
    Faturamento: d.total,
    fill: CHART_COLORS[i % 4],
  }))

  const convenioBarData = byConvenio.slice(0, 8).map(c => ({
    name: c.convenio.length > 20 ? c.convenio.slice(0, 20) + '…' : c.convenio,
    Faturamento: c.total,
  }))

  const procedureBarData = byProcedure.slice(0, 8).map(p => ({
    name: p.procedure.length > 22 ? p.procedure.slice(0, 22) + '…' : p.procedure,
    Faturamento: p.total,
  }))

  const patientBarData = byPatient.slice(0, 8).map(p => ({
    name: p.name.length > 20 ? p.name.slice(0, 20) + '…' : p.name,
    Faturamento: p.total,
  }))

  const roomBarData = byRoom.slice(0, 8).map(r => ({
    name: r.name.length > 20 ? r.name.slice(0, 20) + '…' : r.name,
    Faturamento: r.total,
  }))

  return (
    <div className="space-y-6 page-stagger">
      <PageHeader
        title="Análise Avançada"
        subtitle="Faturamento por forma de pagamento, horário, dia e procedimento"
      />

      {/* Filtros */}
      <div className="card py-4">
        <div className="flex flex-wrap items-center gap-3">
          <div className="flex items-center gap-2">
            <label className="text-xs font-medium text-slate-600">De</label>
            <input
              type="date"
              value={startDate}
              onChange={e => setStartDate(e.target.value)}
              className="input-field py-1.5 text-sm w-36"
            />
          </div>
          <div className="flex items-center gap-2">
            <label className="text-xs font-medium text-slate-600">Até</label>
            <input
              type="date"
              value={endDate}
              onChange={e => setEndDate(e.target.value)}
              className="input-field py-1.5 text-sm w-36"
            />
          </div>
        </div>
      </div>

      {/* KPI tiles */}
      <div className="grid grid-cols-1 sm:grid-cols-4 gap-4">
        <StatTile label="Total faturado" value={currency(totalFaturado)} />
        <StatTile label="Transações" value={String(totalTransacoes)} />
        <StatTile label="Ticket médio" value={currency(ticketMedio)} />
        <StatTile label="Cortesias fechadas" value={String(courtesies?.count ?? 0)} />
      </div>

      {/* Row 1: PieChart + BarChart hora */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Por Forma de Pagamento */}
        {loadingPayment ? <SkeletonCard /> : (
          <div className="card">
            <h3 className="text-sm font-semibold text-slate-900 mb-4">Faturamento por Forma de Pagamento</h3>
            {pieData.length === 0 ? (
              <div className="flex items-center justify-center h-[280px] text-slate-400 text-sm">Sem dados no período</div>
            ) : (
              <ResponsiveContainer width="100%" height={280}>
                <PieChart>
                  <Pie
                    data={pieData}
                    cx="50%"
                    cy="50%"
                    innerRadius={60}
                    outerRadius={100}
                    dataKey="value"
                    paddingAngle={2}
                  >
                    {pieData.map((entry, i) => (
                      <Cell key={i} fill={entry.fill} />
                    ))}
                  </Pie>
                  <Tooltip
                    formatter={(v: number) => [currency(v), 'Total']}
                    contentStyle={{ borderRadius: '12px', border: 'none', boxShadow: '0 8px 24px -4px rgba(0,0,0,0.12)', fontSize: 12 }}
                  />
                  <Legend
                    formatter={(value: string) => <span className="text-xs text-slate-600">{value}</span>}
                    iconType="circle"
                    iconSize={8}
                  />
                </PieChart>
              </ResponsiveContainer>
            )}
          </div>
        )}

        {/* Por Hora do Dia */}
        {loadingHour ? <SkeletonCard /> : (
          <div className="card">
            <h3 className="text-sm font-semibold text-slate-900 mb-4">Faturamento por Hora do Dia</h3>
            {hourBarData.length === 0 ? (
              <div className="flex items-center justify-center h-[280px] text-slate-400 text-sm">Sem dados no período</div>
            ) : (
              <ResponsiveContainer width="100%" height={280}>
                <BarChart data={hourBarData} margin={{ top: 4, right: 4, left: -8, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" vertical={false} opacity={0.3} />
                  <XAxis dataKey="name" tick={{ fontSize: 11, fill: '#94a3b8' }} axisLine={false} tickLine={false} />
                  <YAxis tick={{ fontSize: 11, fill: '#94a3b8' }} axisLine={false} tickLine={false} tickFormatter={yAxisFormatter} />
                  <Tooltip content={<CustomTooltip />} cursor={{ fill: '#f8fafc' }} />
                  <Bar dataKey="Faturamento" radius={[4, 4, 0, 0]} maxBarSize={36}>
                    {hourBarData.map((entry, i) => (
                      <Cell key={i} fill={entry.fill} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            )}
          </div>
        )}
      </div>

      {/* Row 2: BarChart dia semana + BarChart convênio */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Por Dia da Semana */}
        {loadingDow ? <SkeletonCard /> : (
          <div className="card">
            <h3 className="text-sm font-semibold text-slate-900 mb-4">Faturamento por Dia da Semana</h3>
            {dowBarData.length === 0 ? (
              <div className="flex items-center justify-center h-[280px] text-slate-400 text-sm">Sem dados no período</div>
            ) : (
              <ResponsiveContainer width="100%" height={280}>
                <BarChart data={dowBarData} margin={{ top: 4, right: 4, left: -8, bottom: 0 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" vertical={false} opacity={0.3} />
                  <XAxis dataKey="name" tick={{ fontSize: 11, fill: '#94a3b8' }} axisLine={false} tickLine={false} />
                  <YAxis tick={{ fontSize: 11, fill: '#94a3b8' }} axisLine={false} tickLine={false} tickFormatter={yAxisFormatter} />
                  <Tooltip content={<CustomTooltip />} cursor={{ fill: '#f8fafc' }} />
                  <Bar dataKey="Faturamento" radius={[4, 4, 0, 0]} maxBarSize={48}>
                    {dowBarData.map((entry, i) => (
                      <Cell key={i} fill={entry.fill} />
                    ))}
                  </Bar>
                </BarChart>
              </ResponsiveContainer>
            )}
          </div>
        )}

        {/* Por Convênio */}
        {loadingConvenio ? <SkeletonCard /> : (
          <div className="card">
            <h3 className="text-sm font-semibold text-slate-900 mb-4">Faturamento por Convênio</h3>
            {convenioBarData.length === 0 ? (
              <div className="flex items-center justify-center h-[280px] text-slate-400 text-sm">Sem dados no período</div>
            ) : (
              <ResponsiveContainer width="100%" height={280}>
                <BarChart
                  data={convenioBarData}
                  layout="vertical"
                  margin={{ top: 4, right: 16, left: 4, bottom: 0 }}
                >
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" horizontal={false} opacity={0.3} />
                  <XAxis type="number" tick={{ fontSize: 11, fill: '#94a3b8' }} axisLine={false} tickLine={false} tickFormatter={yAxisFormatter} />
                  <YAxis type="category" dataKey="name" tick={{ fontSize: 11, fill: '#64748b' }} axisLine={false} tickLine={false} width={100} />
                  <Tooltip content={<CustomTooltip />} cursor={{ fill: '#f8fafc' }} />
                  <Bar dataKey="Faturamento" fill={CHART_COLORS[1]} radius={[0, 4, 4, 0]} maxBarSize={28} />
                </BarChart>
              </ResponsiveContainer>
            )}
          </div>
        )}
      </div>

      {/* Row 3: Por Procedimento full width */}
      {loadingProcedure ? <SkeletonCard /> : (
        <div className="card">
          <h3 className="text-sm font-semibold text-slate-900 mb-4">Faturamento por Procedimento</h3>
          {procedureBarData.length === 0 ? (
            <div className="flex items-center justify-center h-[280px] text-slate-400 text-sm">Sem dados no período</div>
          ) : (
            <ResponsiveContainer width="100%" height={280}>
              <BarChart
                data={procedureBarData}
                layout="vertical"
                margin={{ top: 4, right: 16, left: 4, bottom: 0 }}
              >
                <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" horizontal={false} opacity={0.3} />
                <XAxis type="number" tick={{ fontSize: 11, fill: '#94a3b8' }} axisLine={false} tickLine={false} tickFormatter={yAxisFormatter} />
                <YAxis type="category" dataKey="name" tick={{ fontSize: 11, fill: '#64748b' }} axisLine={false} tickLine={false} width={130} />
                <Tooltip content={<CustomTooltip />} cursor={{ fill: '#f8fafc' }} />
                <Bar dataKey="Faturamento" fill={CHART_COLORS[0]} radius={[0, 4, 4, 0]} maxBarSize={32} />
              </BarChart>
            </ResponsiveContainer>
          )}
        </div>
      )}

      {/* Row 4: Por Paciente + Por Local */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {loadingPatient ? <SkeletonCard /> : (
          <div className="card">
            <h3 className="text-sm font-semibold text-slate-900 mb-4">Faturamento por Paciente</h3>
            {patientBarData.length === 0 ? (
              <div className="flex items-center justify-center h-[280px] text-slate-400 text-sm">Sem dados no período</div>
            ) : (
              <ResponsiveContainer width="100%" height={280}>
                <BarChart
                  data={patientBarData}
                  layout="vertical"
                  margin={{ top: 4, right: 16, left: 4, bottom: 0 }}
                >
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" horizontal={false} opacity={0.3} />
                  <XAxis type="number" tick={{ fontSize: 11, fill: '#94a3b8' }} axisLine={false} tickLine={false} tickFormatter={yAxisFormatter} />
                  <YAxis type="category" dataKey="name" tick={{ fontSize: 11, fill: '#64748b' }} axisLine={false} tickLine={false} width={110} />
                  <Tooltip content={<CustomTooltip />} cursor={{ fill: '#f8fafc' }} />
                  <Bar dataKey="Faturamento" fill={CHART_COLORS[1]} radius={[0, 4, 4, 0]} maxBarSize={28} />
                </BarChart>
              </ResponsiveContainer>
            )}
          </div>
        )}

        {loadingRoom ? <SkeletonCard /> : (
          <div className="card">
            <h3 className="text-sm font-semibold text-slate-900 mb-4">Faturamento por Local</h3>
            {roomBarData.length === 0 ? (
              <div className="flex items-center justify-center h-[280px] text-slate-400 text-sm">Sem dados no período</div>
            ) : (
              <ResponsiveContainer width="100%" height={280}>
                <BarChart
                  data={roomBarData}
                  layout="vertical"
                  margin={{ top: 4, right: 16, left: 4, bottom: 0 }}
                >
                  <CartesianGrid strokeDasharray="3 3" stroke="#e2e8f0" horizontal={false} opacity={0.3} />
                  <XAxis type="number" tick={{ fontSize: 11, fill: '#94a3b8' }} axisLine={false} tickLine={false} tickFormatter={yAxisFormatter} />
                  <YAxis type="category" dataKey="name" tick={{ fontSize: 11, fill: '#64748b' }} axisLine={false} tickLine={false} width={110} />
                  <Tooltip content={<CustomTooltip />} cursor={{ fill: '#f8fafc' }} />
                  <Bar dataKey="Faturamento" fill={CHART_COLORS[3]} radius={[0, 4, 4, 0]} maxBarSize={28} />
                </BarChart>
              </ResponsiveContainer>
            )}
          </div>
        )}
      </div>
    </div>
  )
}
