// packages/frontend/src/components/layout/SettingsSidebar.vue
<script setup lang="ts">
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { Home, Settings, ChevronRight, PanelLeftClose, PanelLeft } from 'lucide-vue-next'
import { useAuthStore } from '../../stores/auth'
import { getVisibleSettingsNav } from '../../config/settingsNav'
import { useSecretaryPermissions } from '../../composables/useSecretaryPermissions'

const props = defineProps<{ collapsed?: boolean }>()
const emit = defineEmits<{ toggleCollapse: [] }>()

const authStore = useAuthStore()
const router = useRouter()
const route = useRoute()
const { permissions } = useSecretaryPermissions()

const visible = computed(() => getVisibleSettingsNav(authStore.user ?? undefined, permissions.value as Record<string, boolean>))
const initials = computed(() => authStore.user?.name?.split(' ').slice(0, 2).map(n => n[0]).join('').toUpperCase() || 'U')

function isActive(to: string) {
  return route.path === to
}
</script>

<template>
  <aside
    class="bg-white border-r border-slate-200 flex flex-col h-screen flex-shrink-0 select-none overflow-hidden"
    :style="{ width: props.collapsed ? 68 : 256, transition: 'width 0.32s cubic-bezier(.22,1,.36,1)' }"
  >
    <div class="px-2.5 py-3.5 border-b border-slate-100 flex-shrink-0">
      <div v-if="!props.collapsed" class="flex items-center justify-between min-w-0">
        <div class="flex items-center gap-2.5 min-w-0">
          <div class="w-8 h-8 bg-primary-50 rounded-xl flex items-center justify-center border border-primary-100 flex-shrink-0">
            <Settings class="w-4 h-4 text-primary-600" />
          </div>
          <div class="min-w-0">
            <h1 class="text-slate-900 font-semibold text-sm leading-tight truncate">Configurações</h1>
            <p class="text-slate-400 text-[11px]">Preferências</p>
          </div>
        </div>
        <div class="flex items-center gap-1 flex-shrink-0">
          <button class="w-7 h-7 rounded-lg flex items-center justify-center text-slate-400 hover:text-primary-700 hover:bg-primary-50 transition-all duration-150" title="Voltar ao Painel" @click="router.push('/dashboard')">
            <Home class="w-4 h-4" />
          </button>
          <button class="w-7 h-7 flex items-center justify-center text-slate-400 hover:text-primary-700 hover:bg-primary-50 rounded-lg transition-all duration-150" title="Recolher sidebar" @click="emit('toggleCollapse')">
            <PanelLeftClose class="w-4 h-4" />
          </button>
        </div>
      </div>
      <div v-else class="flex items-center justify-between min-w-0">
        <div class="w-7 h-7 bg-primary-50 rounded-lg flex items-center justify-center border border-primary-100 cursor-pointer hover:bg-primary-100 transition-colors" title="Voltar ao Painel" @click="router.push('/dashboard')">
          <Settings class="w-4 h-4 text-primary-600" />
        </div>
        <button class="w-7 h-7 flex items-center justify-center text-primary-500 hover:text-primary-700 hover:bg-primary-50 rounded-lg transition-all duration-150" title="Expandir sidebar" @click="emit('toggleCollapse')">
          <PanelLeft class="w-4.5 h-4.5" />
        </button>
      </div>
    </div>

    <nav class="flex-1 min-h-0 overflow-y-auto px-2 py-3 space-y-0.5 scrollbar-none">
      <p v-if="!props.collapsed" class="section-label mb-3">Opções</p>
      <router-link
        v-for="item in visible"
        :key="item.to"
        :to="item.to"
        :class="['sidebar-link group tooltip-trigger', isActive(item.to) ? 'active' : '']"
      >
        <component :is="item.icon" :class="['w-4.5 h-4.5 flex-shrink-0 transition-all duration-200', isActive(item.to) ? 'text-white' : 'text-slate-400 group-hover:text-primary-600 group-hover:scale-110']" />
        <span class="flex-1 text-sm overflow-hidden transition-all duration-300 whitespace-nowrap" :style="{ opacity: props.collapsed ? 0 : 1, maxWidth: props.collapsed ? '0' : '200px' }">
          {{ item.label }}
        </span>
        <ChevronRight v-if="isActive(item.to) && !props.collapsed" class="w-3.5 h-3.5 opacity-50 flex-shrink-0" />
        <span v-if="props.collapsed" class="tooltip">{{ item.label }}</span>
      </router-link>
    </nav>

    <div class="border-t border-slate-100 p-3 flex-shrink-0">
      <div :class="['flex items-center gap-3 px-2 py-2 rounded-xl', props.collapsed ? 'justify-center' : '']">
        <div class="w-8 h-8 rounded-full overflow-hidden flex-shrink-0 shadow-sm shadow-primary-600/20">
          <img v-if="authStore.user?.avatarUrl" :src="authStore.user.avatarUrl" :alt="authStore.user.name" class="w-full h-full object-cover" />
          <div v-else class="w-full h-full bg-gradient-to-br from-primary-500 to-primary-700 flex items-center justify-center">
            <span class="text-white text-xs font-semibold">{{ initials }}</span>
          </div>
        </div>
        <div v-if="!props.collapsed" class="min-w-0">
          <p class="text-slate-900 text-xs font-semibold truncate leading-snug">{{ authStore.user?.name }}</p>
          <p class="text-slate-400 text-xs truncate">{{ authStore.user?.email }}</p>
        </div>
      </div>
    </div>
  </aside>
</template>

// packages/frontend/src/components/SettingsSidebar.tsx
import { NavLink, useNavigate } from 'react-router-dom'
import { Home, Settings, ChevronRight, PanelLeftClose, PanelLeft } from 'lucide-react'
import { useAuthStore } from '../store/authStore'
import { getVisibleSettingsNav } from '../config/settingsNav'
import { useSecretaryPermissions } from '../hooks/useSecretaryPermissions'

interface SettingsSidebarProps {
  collapsed?: boolean
  onToggleCollapse?: () => void
}

export default function SettingsSidebar({ collapsed = false, onToggleCollapse }: SettingsSidebarProps) {
  const { user } = useAuthStore()
  const navigate = useNavigate()
  const { permissions } = useSecretaryPermissions()
  const visible = getVisibleSettingsNav(user ?? undefined, permissions)

  const initials = user?.name
    ?.split(' ')
    .slice(0, 2)
    .map(n => n[0])
    .join('')
    .toUpperCase() || 'U'

  return (
    <aside
      className="bg-slate-900 flex flex-col h-screen flex-shrink-0 select-none overflow-hidden"
      style={{
        width: collapsed ? 68 : 256,
        transition: 'width 0.32s cubic-bezier(.22,1,.36,1)',
      }}
    >
      {/* Header */}
      <div className="px-2.5 py-3.5 border-b border-white/8 flex-shrink-0">
        {!collapsed ? (
          <div className="flex items-center justify-between min-w-0">
            <div className="flex items-center gap-2.5 min-w-0">
              <div className="w-8 h-8 bg-blue-600/20 rounded-xl flex items-center justify-center border border-blue-500/20 flex-shrink-0">
                <Settings className="w-4 h-4 text-blue-400" />
              </div>
              <div className="min-w-0">
                <h1 className="text-white font-semibold text-sm leading-tight truncate">Configurações</h1>
                <p className="text-slate-500 text-[11px]">Preferências</p>
              </div>
            </div>
            <div className="flex items-center gap-1 flex-shrink-0">
              <button
                onClick={() => navigate('/dashboard')}
                className="w-7 h-7 rounded-lg flex items-center justify-center text-slate-400 hover:text-white hover:bg-white/10 transition-all duration-150"
                title="Voltar ao Painel"
              >
                <Home className="w-4 h-4" />
              </button>
              {onToggleCollapse && (
                <button
                  onClick={onToggleCollapse}
                  className="w-7 h-7 flex items-center justify-center text-slate-400 hover:text-white hover:bg-white/10 rounded-lg transition-all duration-150"
                  title="Recolher sidebar"
                >
                  <PanelLeftClose className="w-4 h-4" />
                </button>
              )}
            </div>
          </div>
        ) : (
          <div className="flex items-center justify-between min-w-0">
            <div
              onClick={() => navigate('/dashboard')}
              className="w-7 h-7 bg-blue-600/20 rounded-lg flex items-center justify-center border border-blue-500/20 cursor-pointer hover:bg-blue-600/30 transition-colors"
              title="Voltar ao Painel"
            >
              <Settings className="w-4 h-4 text-blue-400" />
            </div>
            {onToggleCollapse && (
              <button
                onClick={onToggleCollapse}
                className="w-7 h-7 flex items-center justify-center text-cyan-400 hover:text-white hover:bg-cyan-500/20 rounded-lg transition-all duration-150"
                title="Expandir sidebar"
              >
                <PanelLeft className="w-4.5 h-4.5" />
              </button>
            )}
          </div>
        )}
      </div>

      {/* Nav Items */}
      <nav className="flex-1 min-h-0 overflow-y-auto px-2 py-3 space-y-0.5 scrollbar-none">
        {!collapsed && (
          <p className="section-label mb-3 text-slate-500">Opções</p>
        )}
        {visible.map(({ to, icon: Icon, label }) => (
          <NavLink
            key={to}
            to={to}
            className={({ isActive }) => `sidebar-link group tooltip-trigger ${isActive ? 'active' : ''}`}
          >
            {({ isActive }) => (
              <>
                <Icon className={`w-4.5 h-4.5 flex-shrink-0 transition-all duration-200 ${
                  isActive ? 'text-white' : 'text-slate-400 group-hover:text-white group-hover:scale-110'
                }`} />
                <span
                  className="flex-1 text-sm overflow-hidden transition-all duration-300 whitespace-nowrap"
                  style={{ opacity: collapsed ? 0 : 1, maxWidth: collapsed ? 0 : '200px' }}
                >
                  {label}
                </span>
                {isActive && !collapsed && (
                  <ChevronRight className="w-3.5 h-3.5 opacity-50 flex-shrink-0 animate-fade-in" />
                )}
                {collapsed && <span className="tooltip">{label}</span>}
              </>
            )}
          </NavLink>
        ))}
      </nav>

      {/* User Footer Profile */}
      <div className="border-t border-white/8 p-3 flex-shrink-0">
        <div className={`flex items-center gap-3 px-2 py-2 rounded-xl hover:bg-white/5 transition-colors duration-150 ${collapsed ? 'justify-center' : ''}`}>
          <div className="w-8 h-8 rounded-full overflow-hidden flex-shrink-0 shadow-md shadow-blue-700/30">
            {user?.avatarUrl ? (
              <img src={user.avatarUrl} alt={user.name} className="w-full h-full object-cover" />
            ) : (
              <div className="w-full h-full bg-gradient-to-br from-cyan-500 to-blue-600 flex items-center justify-center">
                <span className="text-white text-xs font-semibold leading-none">{initials}</span>
              </div>
            )}
          </div>
          {!collapsed && (
            <div className="min-w-0">
              <p className="text-white text-xs font-semibold truncate leading-snug">{user?.name}</p>
              <p className="text-slate-500 text-xs truncate">{user?.email}</p>
            </div>
          )}
        </div>
      </div>
    </aside>
  )
}
