// packages/frontend/src/components/Financial/TransactionForm.tsx
import { useEffect } from 'react'
import { useForm } from 'react-hook-form'
import { zodResolver } from '@hookform/resolvers/zod'
import { z } from 'zod'
import { format } from 'date-fns'
import type { Transaction, User, AuthUser, Patient } from '../../types'

const schema = z.object({
  doctorId: z.string().min(1, 'Selecione um médico'),
  patientId: z.string().optional(),
  type: z.enum(['INCOME', 'EXPENSE']),
  amount: z.coerce.number().positive('Valor deve ser positivo'),
  description: z.string().min(2, 'Descrição muito curta'),
  date: z.string().min(1, 'Data obrigatória'),
  status: z.enum(['PENDING', 'PAID', 'CANCELLED']),
  category: z.string().optional(),
})

type FormData = z.infer<typeof schema>

interface Props {
  transaction: Transaction | null
  doctors: User[]
  patients: Patient[]
  currentUser: AuthUser | null
  onSubmit: (data: FormData) => void
  loading: boolean
}

const CATEGORIES = {
  INCOME: ['Consulta', 'Retorno', 'Exame', 'Procedimento', 'Plano de Saúde', 'Outros'],
  EXPENSE: ['Material', 'Equipamento', 'Aluguel', 'Salário', 'Impostos', 'Marketing', 'Outros'],
}

export default function TransactionForm({ transaction, doctors, patients, currentUser, onSubmit, loading }: Props) {
  const { register, handleSubmit, formState: { errors }, setValue, watch } = useForm<FormData>({
    resolver: zodResolver(schema),
    defaultValues: {
      type: 'INCOME',
      status: 'PENDING',
      doctorId: currentUser?.role === 'DOCTOR' ? currentUser.id : '',
    },
  })

  const watchType = watch('type')

  useEffect(() => {
    if (transaction) {
      setValue('doctorId', transaction.doctorId)
      setValue('patientId', transaction.patientId || '')
      setValue('type', transaction.type)
      setValue('amount', transaction.amount)
      setValue('description', transaction.description)
      setValue('date', format(new Date(transaction.date), 'yyyy-MM-dd'))
      setValue('status', transaction.status)
      setValue('category', transaction.category || '')
    } else {
      setValue('date', format(new Date(), 'yyyy-MM-dd'))
    }
  }, [transaction, setValue])

  return (
    <form onSubmit={handleSubmit(onSubmit)} className="space-y-4">
      <div className="grid grid-cols-2 gap-4">
        <div>
          <label className="label">Tipo *</label>
          <div className="flex rounded-lg border border-slate-200 overflow-hidden">
            {[
              { value: 'INCOME', label: 'Receita', active: 'bg-emerald-500 text-white' },
              { value: 'EXPENSE', label: 'Despesa', active: 'bg-red-500 text-white' },
            ].map(({ value, label, active }) => (
              <button
                key={value}
                type="button"
                onClick={() => setValue('type', value as 'INCOME' | 'EXPENSE')}
                className={`flex-1 py-2.5 text-sm font-medium transition-colors ${watchType === value ? active : 'text-slate-500 hover:bg-slate-50'}`}
              >
                {label}
              </button>
            ))}
          </div>
        </div>

        <div>
          <label className="label">Valor (R$) *</label>
          <input
            {...register('amount')}
            type="number"
            step="0.01"
            min="0"
            className="input-field"
            placeholder="0,00"
          />
          {errors.amount && <p className="text-xs text-red-500 mt-1">{errors.amount.message}</p>}
        </div>
      </div>

      {currentUser?.role === 'ADMIN' && (
        <div>
          <label className="label">Médico *</label>
          <select {...register('doctorId')} className="input-field">
            <option value="">Selecione o médico</option>
            {doctors.map(d => (
              <option key={d.id} value={d.id}>Dr(a). {d.name}</option>
            ))}
          </select>
          {errors.doctorId && <p className="text-xs text-red-500 mt-1">{errors.doctorId.message}</p>}
        </div>
      )}

      {watchType === 'INCOME' && (
        <div>
          <label className="label">Paciente (opcional)</label>
          <select {...register('patientId')} className="input-field">
            <option value="">Não informado</option>
            {patients.map(p => (
              <option key={p.id} value={p.id}>{p.name}</option>
            ))}
          </select>
        </div>
      )}

      <div>
        <label className="label">Descrição *</label>
        <input {...register('description')} className="input-field" placeholder="Ex: Consulta - João Silva" />
        {errors.description && <p className="text-xs text-red-500 mt-1">{errors.description.message}</p>}
      </div>

      <div className="grid grid-cols-2 gap-4">
        <div>
          <label className="label">Data *</label>
          <input {...register('date')} type="date" className="input-field" />
          {errors.date && <p className="text-xs text-red-500 mt-1">{errors.date.message}</p>}
        </div>

        <div>
          <label className="label">Categoria</label>
          <select {...register('category')} className="input-field">
            <option value="">Selecione</option>
            {CATEGORIES[watchType]?.map(c => (
              <option key={c} value={c}>{c}</option>
            ))}
          </select>
        </div>
      </div>

      <div>
        <label className="label">Status *</label>
        <select {...register('status')} className="input-field">
          <option value="PENDING">Pendente</option>
          <option value="PAID">Pago</option>
          <option value="CANCELLED">Cancelado</option>
        </select>
      </div>

      <button type="submit" disabled={loading} className="btn-primary w-full mt-2">
        {loading ? (
          <span className="flex items-center gap-2 justify-center">
            <div className="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
            Salvando...
          </span>
        ) : transaction ? 'Atualizar Transação' : 'Adicionar Transação'}
      </button>
    </form>
  )
}

// packages/frontend/src/components/Financial/TransactionForm.vue
<script setup lang="ts">
import { reactive, watch } from 'vue'
import { z } from 'zod'
import { format } from 'date-fns'
import type { Transaction, User, AuthUser, Patient, TransactionType, TransactionStatus } from '../../types'

const schema = z.object({
  doctorId: z.string().min(1, 'Selecione um médico'),
  patientId: z.string().optional(),
  type: z.enum(['INCOME', 'EXPENSE']),
  amount: z.coerce.number().positive('Valor deve ser positivo'),
  description: z.string().min(2, 'Descrição muito curta'),
  date: z.string().min(1, 'Data obrigatória'),
  status: z.enum(['PENDING', 'PAID', 'CANCELLED']),
  category: z.string().optional(),
})

type FormData = z.infer<typeof schema>

const props = defineProps<{
  transaction: Transaction | null
  doctors: User[]
  patients: Patient[]
  currentUser: AuthUser | null
  loading: boolean
}>()

const emit = defineEmits<{ submit: [data: FormData] }>()

const CATEGORIES: Record<TransactionType, string[]> = {
  INCOME: ['Consulta', 'Retorno', 'Exame', 'Procedimento', 'Plano de Saúde', 'Outros'],
  EXPENSE: ['Material', 'Equipamento', 'Aluguel', 'Salário', 'Impostos', 'Marketing', 'Outros'],
}

const TYPE_OPTIONS: Array<{ value: TransactionType; label: string; active: string }> = [
  { value: 'INCOME', label: 'Receita', active: 'bg-emerald-500 text-white' },
  { value: 'EXPENSE', label: 'Despesa', active: 'bg-red-500 text-white' },
]

const form = reactive<{
  doctorId: string
  patientId: string
  type: TransactionType
  amount: number | string
  description: string
  date: string
  status: TransactionStatus
  category: string
}>({
  doctorId: props.currentUser?.role === 'DOCTOR' ? props.currentUser.id : '',
  patientId: '',
  type: 'INCOME',
  amount: '',
  description: '',
  date: format(new Date(), 'yyyy-MM-dd'),
  status: 'PENDING',
  category: '',
})

const errors = reactive<Partial<Record<keyof FormData, string>>>({})

// Mirrors the original react-hook-form `useEffect` that resets the form
// whenever the `transaction` prop changes (edit vs. new).
watch(
  () => props.transaction,
  (transaction) => {
    if (transaction) {
      form.doctorId = transaction.doctorId
      form.patientId = transaction.patientId || ''
      form.type = transaction.type
      form.amount = transaction.amount
      form.description = transaction.description
      form.date = format(new Date(transaction.date), 'yyyy-MM-dd')
      form.status = transaction.status
      form.category = transaction.category || ''
    } else {
      form.date = format(new Date(), 'yyyy-MM-dd')
    }
  },
  { immediate: true }
)

function setType(value: TransactionType) {
  form.type = value
}

function clearErrors() {
  for (const key of Object.keys(errors) as (keyof FormData)[]) {
    delete errors[key]
  }
}

function handleSubmit() {
  clearErrors()
  const parsed = schema.safeParse(form)
  if (!parsed.success) {
    for (const issue of parsed.error.issues) {
      const key = issue.path[0] as keyof FormData
      errors[key] = issue.message
    }
    return
  }
  emit('submit', parsed.data)
}
</script>

<template>
  <form class="space-y-4" @submit.prevent="handleSubmit">
    <div class="grid grid-cols-2 gap-4">
      <div>
        <label class="label">Tipo *</label>
        <div class="flex rounded-lg border border-slate-200 overflow-hidden">
          <button
            v-for="opt in TYPE_OPTIONS"
            :key="opt.value"
            type="button"
            :class="['flex-1 py-2.5 text-sm font-medium transition-colors', form.type === opt.value ? opt.active : 'text-slate-500 hover:bg-slate-50']"
            @click="setType(opt.value)"
          >
            {{ opt.label }}
          </button>
        </div>
      </div>

      <div>
        <label class="label">Valor (R$) *</label>
        <input v-model="form.amount" type="number" step="0.01" min="0" class="input-field" placeholder="0,00" />
        <p v-if="errors.amount" class="text-xs text-red-500 mt-1">{{ errors.amount }}</p>
      </div>
    </div>

    <div v-if="props.currentUser?.role === 'ADMIN'">
      <label class="label">Médico *</label>
      <select v-model="form.doctorId" class="input-field">
        <option value="">Selecione o médico</option>
        <option v-for="d in props.doctors" :key="d.id" :value="d.id">Dr(a). {{ d.name }}</option>
      </select>
      <p v-if="errors.doctorId" class="text-xs text-red-500 mt-1">{{ errors.doctorId }}</p>
    </div>

    <div v-if="form.type === 'INCOME'">
      <label class="label">Paciente (opcional)</label>
      <select v-model="form.patientId" class="input-field">
        <option value="">Não informado</option>
        <option v-for="p in props.patients" :key="p.id" :value="p.id">{{ p.name }}</option>
      </select>
    </div>

    <div>
      <label class="label">Descrição *</label>
      <input v-model="form.description" class="input-field" placeholder="Ex: Consulta - João Silva" />
      <p v-if="errors.description" class="text-xs text-red-500 mt-1">{{ errors.description }}</p>
    </div>

    <div class="grid grid-cols-2 gap-4">
      <div>
        <label class="label">Data *</label>
        <input v-model="form.date" type="date" class="input-field" />
        <p v-if="errors.date" class="text-xs text-red-500 mt-1">{{ errors.date }}</p>
      </div>

      <div>
        <label class="label">Categoria</label>
        <select v-model="form.category" class="input-field">
          <option value="">Selecione</option>
          <option v-for="c in CATEGORIES[form.type]" :key="c" :value="c">{{ c }}</option>
        </select>
      </div>
    </div>

    <div>
      <label class="label">Status *</label>
      <select v-model="form.status" class="input-field">
        <option value="PENDING">Pendente</option>
        <option value="PAID">Pago</option>
        <option value="CANCELLED">Cancelado</option>
      </select>
    </div>

    <button type="submit" :disabled="props.loading" class="btn-primary w-full mt-2">
      <span v-if="props.loading" class="flex items-center gap-2 justify-center">
        <span class="w-4 h-4 border-2 border-white/30 border-t-white rounded-full animate-spin" />
        Salvando...
      </span>
      <template v-else>{{ props.transaction ? 'Atualizar Transação' : 'Adicionar Transação' }}</template>
    </button>
  </form>
</template>
